name: projection_space_exploration
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - notebook
  - jupyterlab
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - umap-learn
  - matplotlib
  - seaborn
  - plotly
  - altair
  - opentsne
  - gym
  - hdbscan
  - pillow
  - vegafusion>=1.4.0
  - vl-convert-python>=0.14.0
